/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

import Addition.AdditionChooseLevel;
import Addition.AdditionEP1;
import Compare.Ch5ChooseLevel;
import Compare.Ch5Compare;
import Counting.CountingChooseLevel;
import LearningNumber.LearningNumbers1;
import Pattern.Ch6ChooseLevel;
import Pattern.Ch6Pattern;
import Subtraction.Ch4ChooseLevel;
import Subtraction.Ch4SubEasy1;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static oop.Opening.HEIGHT;
import static oop.Opening.WIDTH;

/**
 *
 * @author Husna
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form Choose
     */
    public static final String TITLE = "สนุก Kids";
    public static final int WIDTH = 800;
    public static final int HEIGHT = 480;

    public Choose() {
        initComponents();
        setTitle(TITLE);
        setSize(WIDTH, HEIGHT);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        bn_ch3 = new javax.swing.JButton();
        bn_ch6 = new javax.swing.JButton();
        bn_ch5 = new javax.swing.JButton();
        bn_ch4 = new javax.swing.JButton();
        bn_ch2 = new javax.swing.JButton();
        bn_ch1 = new javax.swing.JButton();
        next4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bn_ch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/3.png"))); // NOI18N
        bn_ch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch3ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch3);
        bn_ch3.setBounds(530, 50, 216, 170);

        bn_ch6.setBackground(new java.awt.Color(255, 204, 255));
        bn_ch6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/6.PNG"))); // NOI18N
        bn_ch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch6ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch6);
        bn_ch6.setBounds(540, 240, 216, 170);

        bn_ch5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/5.png"))); // NOI18N
        bn_ch5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch5ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch5);
        bn_ch5.setBounds(290, 260, 216, 170);

        bn_ch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/4.png"))); // NOI18N
        bn_ch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch4ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch4);
        bn_ch4.setBounds(40, 250, 216, 170);

        bn_ch2.setBackground(new java.awt.Color(153, 255, 204));
        bn_ch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/2.png"))); // NOI18N
        bn_ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch2ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch2);
        bn_ch2.setBounds(290, 60, 216, 170);

        bn_ch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/1.png"))); // NOI18N
        bn_ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_ch1ActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ch1);
        bn_ch1.setBounds(40, 60, 220, 170);

        next4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/previous.png"))); // NOI18N
        next4.setOpaque(false);
        next4.setContentAreaFilled(false);
        next4.setBorderPainted(false);
        next4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next4ActionPerformed(evt);
            }
        });
        getContentPane().add(next4);
        next4.setBounds(0, 0, 40, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/choose/chosse.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-150, 0, 1020, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn_ch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch4ActionPerformed

        Ch4ChooseLevel c = new Ch4ChooseLevel();
        c.setVisible(true);
        close();

    }//GEN-LAST:event_bn_ch4ActionPerformed

    private void bn_ch5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch5ActionPerformed
        Ch5ChooseLevel c5 = new Ch5ChooseLevel();
        c5.setVisible(true);
        close();

    }//GEN-LAST:event_bn_ch5ActionPerformed

    private void bn_ch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch6ActionPerformed
        Ch6ChooseLevel c = new Ch6ChooseLevel();
        c.setVisible(true);
        close();
    }//GEN-LAST:event_bn_ch6ActionPerformed

    private void bn_ch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch3ActionPerformed
        AdditionChooseLevel a = new AdditionChooseLevel();
        a.setVisible(true);
        close();
    }//GEN-LAST:event_bn_ch3ActionPerformed

    private void bn_ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch2ActionPerformed
        CountingChooseLevel c = new CountingChooseLevel();
        c.setVisible(true);
        close();
    }//GEN-LAST:event_bn_ch2ActionPerformed

    private void bn_ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_ch1ActionPerformed
       LearningNumbers1 t = new LearningNumbers1();
        t.setVisible(true);
        close();
    }//GEN-LAST:event_bn_ch1ActionPerformed

    private void next4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next4ActionPerformed
        Opening o = new Opening();
        o.setVisible(true);
        close();
    }//GEN-LAST:event_next4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_ch1;
    private javax.swing.JButton bn_ch2;
    private javax.swing.JButton bn_ch3;
    private javax.swing.JButton bn_ch4;
    private javax.swing.JButton bn_ch5;
    private javax.swing.JButton bn_ch6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton next4;
    // End of variables declaration//GEN-END:variables
}
