/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;

import java.awt.event.WindowEvent;
import java.awt.geom.AffineTransform;
import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author Husna
 */
public class Opening extends javax.swing.JFrame{

    /**
     * Creates new form Opening
     */
    public static final String TITLE = "สนุก Kids";
	public static final int WIDTH = 800;
	public static final int HEIGHT = 480;


    
    
    
    
    public Opening() {
        initComponents();
        setTitle(TITLE);
        setSize(WIDTH, HEIGHT);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    

    
    
    public void close(){
       this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bn_play = new javax.swing.JButton();
        bn_ex = new javax.swing.JButton();
        bn_how = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bn_play.setBackground(java.awt.SystemColor.textHighlightText);
        bn_play.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        bn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bnplay.png"))); // NOI18N
        bn_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bn_playMouseEntered(evt);
            }
        });
        bn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_playActionPerformed(evt);
            }
        });
        getContentPane().add(bn_play);
        bn_play.setBounds(460, 190, 220, 100);

        bn_ex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bnex1.png"))); // NOI18N
        bn_ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_exActionPerformed(evt);
            }
        });
        getContentPane().add(bn_ex);
        bn_ex.setBounds(630, 340, 110, 50);

        bn_how.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bnhow1.png"))); // NOI18N
        bn_how.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_howActionPerformed(evt);
            }
        });
        getContentPane().add(bn_how);
        bn_how.setBounds(350, 340, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/avatar2 (1)_1.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, -20, 300, 470);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/head2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 0, 540, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/main-2-1.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void bn_exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_exActionPerformed
        close();
    }//GEN-LAST:event_bn_exActionPerformed

    private void bn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_playActionPerformed
        Choose c = new Choose();
        c.setVisible(true);
        close();
    }//GEN-LAST:event_bn_playActionPerformed

    private void bn_playMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bn_playMouseEntered
     
    }//GEN-LAST:event_bn_playMouseEntered

    private void bn_howActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_howActionPerformed
        HowTo h = new HowTo();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_bn_howActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opening().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton bn_ex;
    private javax.swing.JButton bn_how;
    private javax.swing.JButton bn_play;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
