/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LearningNumber;

import static Addition.AdditionEP2.HEIGHT;
import static Addition.AdditionEP2.TITLE;
import static Addition.AdditionEP2.WIDTH;
import Sounds.CorrectSound;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import oop.Choose;

import sun.audio.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author smytt
 */
public class LearningNumbers1 extends javax.swing.JFrame {
    public static final String TITLE = "สนุก Kids";
    public static final int WIDTH = 800;
    public static final int HEIGHT = 480;

    /**
     * Creates new form LearningNumbers1
     */
    public LearningNumbers1() {
        initComponents();
        setTitle(TITLE);
        setSize(WIDTH, HEIGHT);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    public void close() {
        this.setVisible(false);
        this.dispose();
    }
        
//    public String[] getImages() {
//        File file = new File(getClass().getResource("/res/learnnumber").getFile());
//        String[] imagesList = file.list();
//        return imagesList;
//    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        three = new javax.swing.JButton();
        six = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        next = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        three.setOpaque(false);
        three.setContentAreaFilled(false);
        three.setBorderPainted(false);
        three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/3.png"))); // NOI18N
        three.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three);
        three.setBounds(530, 80, 210, 180);

        six.setOpaque(false);
        six.setContentAreaFilled(false);
        six.setBorderPainted(false);
        six.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/6.png"))); // NOI18N
        six.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel1.add(six);
        six.setBounds(530, 270, 210, 180);

        four.setOpaque(false);
        four.setContentAreaFilled(false);
        four.setBorderPainted(false);
        four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/4.png"))); // NOI18N
        four.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four);
        four.setBounds(50, 270, 210, 180);

        five.setOpaque(false);
        five.setContentAreaFilled(false);
        five.setBorderPainted(false);
        five.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/5.png"))); // NOI18N
        five.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five);
        five.setBounds(290, 270, 210, 180);

        one.setOpaque(false);
        one.setContentAreaFilled(false);
        one.setBorderPainted(false);
        one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/1.png"))); // NOI18N
        one.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one);
        one.setBounds(50, 80, 210, 180);

        two.setOpaque(false);
        two.setContentAreaFilled(false);
        two.setBorderPainted(false);
        two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/2.png"))); // NOI18N
        two.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two);
        two.setBounds(290, 80, 210, 180);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/learnnumber/next.png"))); // NOI18N
        next.setOpaque(false);
        next.setContentAreaFilled(false);
        next.setBorderPainted(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(740, 10, 40, 60);

        next1.setFont(new java.awt.Font("Layiji MaHaNiYom V1.61", 0, 24)); // NOI18N
        next1.setText("ถัดไป");
        next1.setOpaque(false);
        next1.setContentAreaFilled(false);
        next1.setBorderPainted(false);
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        jPanel1.add(next1);
        next1.setBounds(650, 20, 130, 40);

        home.setFont(new java.awt.Font("Layiji MaHaNiYom V1.61", 0, 18)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/home_4.png"))); // NOI18N
        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(0, 0, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bgsub.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound3.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_threeActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound6.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sixActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound5.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound4.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fourActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound2.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        try {
            Clip clip = AudioSystem.getClip();
            AudioInputStream audio = AudioSystem.getAudioInputStream(CorrectSound.class.getResourceAsStream("/res/learnnumber/sound1.wav"));
            clip.open(audio);
            clip.start();
            Thread.sleep(1500);
            clip.close();
            
        } catch (Exception ex) {
            Logger.getLogger(LearningNumbers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oneActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        LearningNumbers2 t = new LearningNumbers2();
        t.setVisible(true);
        close();
    }//GEN-LAST:event_nextActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        LearningNumbers2 t = new LearningNumbers2();
        t.setVisible(true);
        close();
    }//GEN-LAST:event_next1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Choose c = new Choose();
        c.setVisible(true);
        close();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningNumbers1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningNumbers1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningNumbers1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningNumbers1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningNumbers1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JButton next1;
    private javax.swing.JButton one;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
